apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml        
  - namespace.yaml      # add
  - clusterissuer-prod.yaml

images:
  - name: __MCP_IMAGE_PLACEHOLDER__
    newName: <YOUR_ACR_NAME>.azurecr.io/mcp-wiki-server
    newTag: v1.0.1
patches:
  - target:
      kind: Ingress
      name: mcp-wiki-https
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: mcp-https.<INGRESS_DASHED_EXTERNAL_IP>.sslip.io
      - op: replace
        path: /spec/rules/0/host
        value: mcp-https.<INGRESS_DASHED_EXTERNAL_IP>.sslip.io